version: '3.7'

services:
  backend:
    build: .
    command: python Backend/apps/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./Backend/.env

  teleram_bot:
    build: .
    command: python TelegramBot/core/main.py
    env_file:
      - ./TelegramBot/.env
    depends_on:
      - redis
      - backend

  redis:
    image: redis:alpine
    ports:
      - 6379:6379