# Generated by Django 4.2 on 2023-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'default_related_name': 'images', 'verbose_name': 'картинка', 'verbose_name_plural': 'галерея'},
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='upload',
        ),
    ]
